In [2]:
import pandas as pd
import os
import sys

In [9]:
star_short=pd.read_csv('star_transects.csv', nrows=10)

In [10]:
star_short

,FID,site,obs_time,longitude,latitude,live_basal_area,total_basal_area,persist,crust,dist,...,mid_d,mid_b,crn,over_g,over_d,over_b,num_points,unoccluded,obs_key,geom
0,star_transects.fid--4082306b_169795d9ed3_-1028,tas006,2011-12-07,147.4487,-42.1797,0.0000,NaN,0.00,13.67,0.00,...,0.00,0.00,0.00,0.00,0,0,300,300,14744873_04217967_20111207_000000,POINT (147.4487292 -42.17966521)
1,star_transects.fid--4082306b_169795d9ed3_-1027,sa_e_saal_23,2012-04-24,139.9750,-31.3893,0.0000,NaN,9.33,33.33,2.33,...,2.00,8.33,0.00,0.00,0,0,300,300,13997501_03138928_20120424_000000,POINT (139.975014 -31.389277)
2,star_transects.fid--4082306b_169795d9ed3_-1026,sa_e_saal_1a,2011-05-12,138.2382,-30.8612,0.0000,NaN,9.33,31.00,1.33,...,4.00,2.33,0.00,0.00,0,0,300,300,13823818_03086124_20110512_000000,POINT (138.238179 -30.861235)
3,star_transects.fid--4082306b_169795d9ed3_-1025,sa_w_saal_07,2011-04-15,134.6890,-27.9134,0.0000,NaN,5.33,12.00,0.00,...,4.33,1.33,0.00,0.00,0,0,300,300,13468896_02791339_20110415_000000,POINT (134.688957 -27.913389)
4,star_transects.fid--4082306b_169795d9ed3_-1024,nsw035,2011-06-19,143.6309,-31.5040,0.0000,NaN,0.00,22.33,0.33,...,0.00,0.00,0.00,0.00,0,0,300,300,14363092_03150399_20110619_000000,POINT (143.630919 -31.50399)
5,star_transects.fid--4082306b_169795d9ed3_-1023,wa_pilb_028,2011-08-25,120.2187,-20.0410,0.0000,NaN,0.33,33.00,0.67,...,0.00,0.00,0.00,0.00,0,0,300,300,12021868_02004097_20110825_000000,POINT (120.218683 -20.040966)
6,star_transects.fid--4082306b_169795d9ed3_-1022,sa_aw_05,2012-12-02,130.8021,-30.2162,0.0000,NaN,1.33,11.00,0.00,...,1.67,9.00,0.00,0.00,0,0,300,300,13080208_03021619_20121202_000000,POINT (130.8020831 -30.21618699)
7,star_transects.fid--4082306b_169795d9ed3_-1021,sa_w_saal_35a,2012-12-04,135.4910,-30.2901,0.0000,NaN,8.00,57.33,0.00,...,0.33,8.67,0.00,0.00,0,0,300,300,13549101_03029011_20121204_000000,POINT (135.491013 -30.29011313)
8,star_transects.fid--4082306b_169795d9ed3_-1020,nsw063,2012-04-20,142.0314,-29.3002,0.0000,NaN,0.00,22.33,0.33,...,0.00,0.00,0.00,0.00,0,0,300,300,14203142_02930024_20120420_000000,POINT (142.031416 -29.300243)
9,star_transects.fid--4082306b_169795d9ed3_-101f,kal_wa_049,2011-05-30,121.3214,-30.7904,1.4286,NaN,12.65,46.99,0.38,...,3.33,5.00,17.67,9.67,3,5,300,266,12132141_03079041_20110530_000000,POINT (121.321408 -30.79041)